name: PHPUnit

on:
  push:

jobs:
  phpunit:
    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.0", "8.1", "8.2", "latest"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP Packages
        uses: php-actions/composer@v6

      - name: Run Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          php_version: ${{ matrix.php_version }}
          php_extensions: "xdebug"
          coverage_clover: "build/logs/clover.xml"
